when:
  - event: [push, pull_request, manual]

services:
  - name: postgres
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: postgres

steps:
  - name: bin-ci
    image: registry.metawave.ch/metawave/trivista-ci:latest
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432
      OIDC_LOGIN_GROUP: trivista_users
    commands:
      - until pg_isready -h postgres -q; do sleep 1; done
      - bin/ci
